nome_do_aluno = input("Olá Aluno do Programa Capacita Brasil, por favor, digite seu nome para que geremos um cabeçalho para voce: ")
print("Capacita Brasil – Ciclo 2")
print("Disciplina: Lógica de programação")
print("Professora: Patrícia Vieira")
print("Aluno(a ): ", nome_do_aluno)